version: '3.5'

services:
  blog_database:
    image: 'postgres:14.5'
    container_name: 'blog_database'
    restart: always
    ports:
      - '5411:5432'
    env_file:
      - ./.env


  blog_api:
    container_name: 'blog_api'
    build: .
    ports:
      - "8000:8000"
    command: ["/bin/bash", "-c", "alembic upgrade head && uvicorn src.__main__:app --host 0.0.0.0 --port 8000"]
    env_file:
      - ./.env
    depends_on:
      - blog_database
    restart: always